### PR TITLE
Fix AttributeError on no match.

### PR DESCRIPTION
**Pull request by Raphaelwuhao**

### CODE REVIEW

**Comment by gyh1621** [comment]
please provide a no matching case

**Comment by Raphaelwuhao** [comment]
@gyh1621 For example I got this error msg on local:

```getsub /Volumes/Elements/电影/仓科加奈-海岸天使.MKV --debug
no valid path specfied,download sub file to video file location.

├  仓科加奈-海岸天使.MKV
├  /Volumes/Elements/电影
├
├  error:unknown error. try again.

===============================FAILED LIST===============================

 1. name: 仓科加奈-海岸天使.MKV
    path: /Volumes/Elements/电影
    info: unknown error. try again.
    TRACE_BACK: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/getsub/main.py", line 646, in start
    downloader.get_subtitles(tuple(keywords), info_dict)
  File "/Library/Python/2.7/site-packages/getsub/zimuzu.py", line 47, in get_subtitles
    tab_text = bs_obj.find('div', {'class': 'article-tab'}).text
AttributeError: 'NoneType' object has no attribute 'text'


total: 1  success: 0  fail: 1```

**Comment by gyh1621** [comment]
I looked into it and found out it's because zimuzu's URL changed from "zmz2019.com" to "rrys2019.com". I updated the URL and published a new version. Please upgrade to the newest version(1.7.2).

Thanks for the PR anyway : )

**Comment by Raphaelwuhao** [comment]
cool.

**Pull request closed without merging**
